spring:
  application:
    name: gateway
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: ${DEPLOY_ENV:dev}
jasypt:
  encryptor:
    password: ${DEPLOY_PWD:123456}
