spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        group: DEFAULT_GROUP
        server-addr: 127.0.0.1:8848
        refresh-enabled: true
  config:
    import:
      - optional:nacos:ums.properties
